---
# This playbook installs and configures Apache Spark

- file:
    path: /hadoop/spark
    state: directory
    mode: 0755

- unarchive:
    src: http://apache.mirrors.pair.com/spark/spark-2.1.1/spark-2.1.1-bin-hadoop2.7.tgz -o spark-2.1.1-bin-hadoop2.7.tgz
    dest: /hadoop/spark
    remote_src: True
    extra_opts: "--strip-components=1"
    creates: /hadoop/spark/LICENSE

- file:
    src: /hadoop/share/hadoop/tools/lib/hadoop-aws-2.7.3.jar
    dest: /hadoop/spark/jars/hadoop-aws-2.7.3.jar
    state: link

- file:
    src: /hadoop/share/hadoop/tools/lib/aws-java-sdk-1.7.4.jar
    dest: /hadoop/spark/jars/aws-java-sdk-1.7.4.jar
    state: link

- file:
    src: /hadoop/hive/conf/hive-site.xml
    dest: /hadoop/spark/conf/hive-site.xml
    state: link
