---
# This playbook installs and configures Apache Spark

- file:
    path: /hadoop/spark
    state: directory
    mode: 0755


- unarchive:
    src: "{{ tarball_prefix }}/spark-2.1.1-bin-hadoop2.7.tgz"
    dest: /hadoop/spark
    remote_src: True
    extra_opts: "--strip-components=1"
    creates: /hadoop/spark/LICENSE

- name: Configure profile
  template: src=profile.j2 dest=/etc/profile.d/spark.sh
  tags: hadoop

- name: Configure Spark environment file
  template: src=spark-env.j2 dest=/hadoop/spark/conf/spark-env.sh mode=0755
  tags: hadoop

- file:
    src: /hadoop/share/hadoop/tools/lib/hadoop-aws-2.7.3.jar
    dest: /hadoop/spark/jars/hadoop-aws-2.7.3.jar
    state: link

- file:
    src: /hadoop/share/hadoop/tools/lib/aws-java-sdk-1.7.4.jar
    dest: /hadoop/spark/jars/aws-java-sdk-1.7.4.jar
    state: link

- name: Configure hive-site file
  template: src=hive-site.j2 dest=/hadoop/spark/conf/hive-site.xml
  tags: hive
  when:
  - head_group in group_names
