---
# This playbook contains common plays that will be run on all nodes.

- unarchive:
    src: http://apache.mirrors.pair.com/hadoop/common/hadoop-2.7.3/hadoop-2.7.3.tar.gz
    dest: /hadoop
    remote_src: True
    extra_opts: ['--skip', '1']
